namespace AmazonOrderAPI.Business.Common.EnumOps
{
    public enum EnumReferenceRecords
    {
        OrderCreated = 1,
        OrderItemsCreated = 2,
        OrderItemsRead = 3,
        InvalidSKU = 4,
        Unshipped = 5,
        PartiallyShipped = 6,
        Other = 7,
        MFN = 8,
        PickupRequestFailed = 10,
        OrderAcknowledgeStarted = 11,
        OrderAcknowledgeSuccessful = 12,
        OrderAcknowledgeFailed = 13,
        OrderFulfillmentStarted = 14,
        OrderFulfillmentSuccessful = 15,
        OrderFulfillmentFailed = 16,
        IN_Std_Dom_2_50k_cod = 17,
        IN_Std_Dom_2_50k = 18,
        IN_Exp_Dom_2 = 19,
        IN_EZ_Remote = 20,
        Std_IN_EZ_Local = 21,
        Std_IN_EZ_Local_COD = 22,
        Std_IN_EZ_Metro = 23,
        Std_IN_EZ_Metro_COD = 24,
        Std_IN_EZ_National = 25,
        Std_IN_EZ_National_COD = 26,
        Std_IN_EZ_Remote = 27,
        DD_IN_EZ_COD1 = 28,
        DD_IN_EZ_COD2 = 29,
        SDD_IN_EZ_COD = 30,
        in_easyship_std = 31,
        //FeedSubmitted = 32,
        //FeedProcessed = 33,
        //FeedCancelled = 34,
        //AcknowledgementFeed = 35,
        //FulfillmentFeed = 36,
        AnyOfferChanged = 32,
        FeedProcessingFinished = 33,
        FeePromotion = 34,
        FulfillmentOrderStatus = 35,
        ReportProcessingFinished = 36,
        FBAOutboundShipmentStatus = 37
    }
}