//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Address", Namespace="", IsNullable=false)]
public partial class AddressType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    private string formalTitleField;
    
    private string givenNameField;
    
    private string familyNameField;
    
    private string addressFieldOneField;
    
    private string addressFieldTwoField;
    
    private string addressFieldThreeField;
    
    private string cityField;
    
    private string countyField;
    
    private string stateOrRegionField;
    
    private string postalCodeField;
    
    private string countryCodeField;
    
    private PhoneNumberType[] phoneNumberField;
    
    private bool isDefaultShippingField;
    
    private bool isDefaultShippingFieldSpecified;
    
    private bool isDefaultBillingField;
    
    private bool isDefaultBillingFieldSpecified;
    
    private bool isDefaultOneClickField;
    
    private bool isDefaultOneClickFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FormalTitle {
        get {
            return this.formalTitleField;
        }
        set {
            this.formalTitleField = value;
            this.RaisePropertyChanged("FormalTitle");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string GivenName {
        get {
            return this.givenNameField;
        }
        set {
            this.givenNameField = value;
            this.RaisePropertyChanged("GivenName");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FamilyName {
        get {
            return this.familyNameField;
        }
        set {
            this.familyNameField = value;
            this.RaisePropertyChanged("FamilyName");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AddressFieldOne {
        get {
            return this.addressFieldOneField;
        }
        set {
            this.addressFieldOneField = value;
            this.RaisePropertyChanged("AddressFieldOne");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AddressFieldTwo {
        get {
            return this.addressFieldTwoField;
        }
        set {
            this.addressFieldTwoField = value;
            this.RaisePropertyChanged("AddressFieldTwo");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AddressFieldThree {
        get {
            return this.addressFieldThreeField;
        }
        set {
            this.addressFieldThreeField = value;
            this.RaisePropertyChanged("AddressFieldThree");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
            this.RaisePropertyChanged("City");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string County {
        get {
            return this.countyField;
        }
        set {
            this.countyField = value;
            this.RaisePropertyChanged("County");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string StateOrRegion {
        get {
            return this.stateOrRegionField;
        }
        set {
            this.stateOrRegionField = value;
            this.RaisePropertyChanged("StateOrRegion");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
            this.RaisePropertyChanged("PostalCode");
        }
    }
    
    /// <remarks/>
    public string CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
            this.RaisePropertyChanged("CountryCode");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PhoneNumber")]
    public PhoneNumberType[] PhoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
            this.RaisePropertyChanged("PhoneNumber");
        }
    }
    
    /// <remarks/>
    public bool isDefaultShipping {
        get {
            return this.isDefaultShippingField;
        }
        set {
            this.isDefaultShippingField = value;
            this.RaisePropertyChanged("isDefaultShipping");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isDefaultShippingSpecified {
        get {
            return this.isDefaultShippingFieldSpecified;
        }
        set {
            this.isDefaultShippingFieldSpecified = value;
            this.RaisePropertyChanged("isDefaultShippingSpecified");
        }
    }
    
    /// <remarks/>
    public bool isDefaultBilling {
        get {
            return this.isDefaultBillingField;
        }
        set {
            this.isDefaultBillingField = value;
            this.RaisePropertyChanged("isDefaultBilling");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isDefaultBillingSpecified {
        get {
            return this.isDefaultBillingFieldSpecified;
        }
        set {
            this.isDefaultBillingFieldSpecified = value;
            this.RaisePropertyChanged("isDefaultBillingSpecified");
        }
    }
    
    /// <remarks/>
    public bool isDefaultOneClick {
        get {
            return this.isDefaultOneClickField;
        }
        set {
            this.isDefaultOneClickField = value;
            this.RaisePropertyChanged("isDefaultOneClick");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isDefaultOneClickSpecified {
        get {
            return this.isDefaultOneClickFieldSpecified;
        }
        set {
            this.isDefaultOneClickFieldSpecified = value;
            this.RaisePropertyChanged("isDefaultOneClickSpecified");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PhoneNumberType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private PhoneNumberTypeType typeField;
    
    private bool typeFieldSpecified;
    
    private string descriptionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PhoneNumberTypeType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
            this.RaisePropertyChanged("Type");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
            this.RaisePropertyChanged("TypeSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
            this.RaisePropertyChanged("Description");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="normalizedString")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
            this.RaisePropertyChanged("Value");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum PhoneNumberTypeType {
    
    /// <remarks/>
    Voice,
    
    /// <remarks/>
    Fax,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class WeightDimension : object, System.ComponentModel.INotifyPropertyChanged {
    
    private WeightUnitOfMeasure unitOfMeasureField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WeightUnitOfMeasure unitOfMeasure {
        get {
            return this.unitOfMeasureField;
        }
        set {
            this.unitOfMeasureField = value;
            this.RaisePropertyChanged("unitOfMeasure");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
            this.RaisePropertyChanged("Value");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum WeightUnitOfMeasure {
    
    /// <remarks/>
    GR,
    
    /// <remarks/>
    KG,
    
    /// <remarks/>
    OZ,
    
    /// <remarks/>
    LB,
    
    /// <remarks/>
    MG,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LengthDimension : object, System.ComponentModel.INotifyPropertyChanged {
    
    private LengthUnitOfMeasure unitOfMeasureField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LengthUnitOfMeasure unitOfMeasure {
        get {
            return this.unitOfMeasureField;
        }
        set {
            this.unitOfMeasureField = value;
            this.RaisePropertyChanged("unitOfMeasure");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
            this.RaisePropertyChanged("Value");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum LengthUnitOfMeasure {
    
    /// <remarks/>
    MM,
    
    /// <remarks/>
    CM,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    IN,
    
    /// <remarks/>
    FT,
    
    /// <remarks/>
    inches,
    
    /// <remarks/>
    feet,
    
    /// <remarks/>
    meters,
    
    /// <remarks/>
    decimeters,
    
    /// <remarks/>
    centimeters,
    
    /// <remarks/>
    millimeters,
    
    /// <remarks/>
    micrometers,
    
    /// <remarks/>
    nanometers,
    
    /// <remarks/>
    picometers,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class WeightIntegerDimension : object, System.ComponentModel.INotifyPropertyChanged {
    
    private WeightUnitOfMeasure unitOfMeasureField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WeightUnitOfMeasure unitOfMeasure {
        get {
            return this.unitOfMeasureField;
        }
        set {
            this.unitOfMeasureField = value;
            this.RaisePropertyChanged("unitOfMeasure");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="positiveInteger")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
            this.RaisePropertyChanged("Value");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AgeRecommendedDimension : object, System.ComponentModel.INotifyPropertyChanged {
    
    private AgeRecommendedUnitOfMeasure unitOfMeasureField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AgeRecommendedUnitOfMeasure unitOfMeasure {
        get {
            return this.unitOfMeasureField;
        }
        set {
            this.unitOfMeasureField = value;
            this.RaisePropertyChanged("unitOfMeasure");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="positiveInteger")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
            this.RaisePropertyChanged("Value");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum AgeRecommendedUnitOfMeasure {
    
    /// <remarks/>
    months,
    
    /// <remarks/>
    years,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MinimumAgeRecommendedDimension : object, System.ComponentModel.INotifyPropertyChanged {
    
    private AgeRecommendedUnitOfMeasure unitOfMeasureField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AgeRecommendedUnitOfMeasure unitOfMeasure {
        get {
            return this.unitOfMeasureField;
        }
        set {
            this.unitOfMeasureField = value;
            this.RaisePropertyChanged("unitOfMeasure");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="nonNegativeInteger")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
            this.RaisePropertyChanged("Value");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Battery : object, System.ComponentModel.INotifyPropertyChanged {
    
    private bool areBatteriesIncludedField;
    
    private bool areBatteriesIncludedFieldSpecified;
    
    private bool areBatteriesRequiredField;
    
    private bool areBatteriesRequiredFieldSpecified;
    
    private BatteryBatterySubgroup[] batterySubgroupField;
    
    /// <remarks/>
    public bool AreBatteriesIncluded {
        get {
            return this.areBatteriesIncludedField;
        }
        set {
            this.areBatteriesIncludedField = value;
            this.RaisePropertyChanged("AreBatteriesIncluded");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AreBatteriesIncludedSpecified {
        get {
            return this.areBatteriesIncludedFieldSpecified;
        }
        set {
            this.areBatteriesIncludedFieldSpecified = value;
            this.RaisePropertyChanged("AreBatteriesIncludedSpecified");
        }
    }
    
    /// <remarks/>
    public bool AreBatteriesRequired {
        get {
            return this.areBatteriesRequiredField;
        }
        set {
            this.areBatteriesRequiredField = value;
            this.RaisePropertyChanged("AreBatteriesRequired");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AreBatteriesRequiredSpecified {
        get {
            return this.areBatteriesRequiredFieldSpecified;
        }
        set {
            this.areBatteriesRequiredFieldSpecified = value;
            this.RaisePropertyChanged("AreBatteriesRequiredSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BatterySubgroup")]
    public BatteryBatterySubgroup[] BatterySubgroup {
        get {
            return this.batterySubgroupField;
        }
        set {
            this.batterySubgroupField = value;
            this.RaisePropertyChanged("BatterySubgroup");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class BatteryBatterySubgroup : object, System.ComponentModel.INotifyPropertyChanged {
    
    private BatteryBatterySubgroupBatteryType batteryTypeField;
    
    private string numberOfBatteriesField;
    
    /// <remarks/>
    public BatteryBatterySubgroupBatteryType BatteryType {
        get {
            return this.batteryTypeField;
        }
        set {
            this.batteryTypeField = value;
            this.RaisePropertyChanged("BatteryType");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfBatteries {
        get {
            return this.numberOfBatteriesField;
        }
        set {
            this.numberOfBatteriesField = value;
            this.RaisePropertyChanged("NumberOfBatteries");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum BatteryBatterySubgroupBatteryType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("battery_type_2/3A")]
    battery_type_23A,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("battery_type_4/3A")]
    battery_type_43A,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("battery_type_4/5A")]
    battery_type_45A,
    
    /// <remarks/>
    battery_type_9v,
    
    /// <remarks/>
    battery_type_12v,
    
    /// <remarks/>
    battery_type_a,
    
    /// <remarks/>
    battery_type_a76,
    
    /// <remarks/>
    battery_type_aa,
    
    /// <remarks/>
    battery_type_aaa,
    
    /// <remarks/>
    battery_type_aaaa,
    
    /// <remarks/>
    battery_type_c,
    
    /// <remarks/>
    battery_type_cr123a,
    
    /// <remarks/>
    battery_type_cr2,
    
    /// <remarks/>
    battery_type_cr5,
    
    /// <remarks/>
    battery_type_d,
    
    /// <remarks/>
    battery_type_lithium_ion,
    
    /// <remarks/>
    battery_type_lithium_metal,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("battery_type_L-SC")]
    battery_type_LSC,
    
    /// <remarks/>
    battery_type_p76,
    
    /// <remarks/>
    battery_type_product_specific,
    
    /// <remarks/>
    battery_type_SC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum FulfillmentMethod {
    
    /// <remarks/>
    Ship,
    
    /// <remarks/>
    InStorePickup,
    
    /// <remarks/>
    MerchantDelivery,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum FulfillmentServiceLevel {
    
    /// <remarks/>
    Standard,
    
    /// <remarks/>
    Expedited,
    
    /// <remarks/>
    Scheduled,
    
    /// <remarks/>
    NextDay,
    
    /// <remarks/>
    SecondDay,
    
    /// <remarks/>
    Next,
    
    /// <remarks/>
    Second,
    
    /// <remarks/>
    Priority,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum CarrierCode {
    
    /// <remarks/>
    USPS,
    
    /// <remarks/>
    UPS,
    
    /// <remarks/>
    UPSMI,
    
    /// <remarks/>
    FedEx,
    
    /// <remarks/>
    DHL,
    
    /// <remarks/>
    Fastway,
    
    /// <remarks/>
    GLS,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("GO!")]
    GO,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Hermes Logistik Gruppe")]
    HermesLogistikGruppe,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Royal Mail")]
    RoyalMail,
    
    /// <remarks/>
    Parcelforce,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("City Link")]
    CityLink,
    
    /// <remarks/>
    TNT,
    
    /// <remarks/>
    Target,
    
    /// <remarks/>
    SagawaExpress,
    
    /// <remarks/>
    NipponExpress,
    
    /// <remarks/>
    YamatoTransport,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("DHL Global Mail")]
    DHLGlobalMail,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("UPS Mail Innovations")]
    UPSMailInnovations,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("FedEx SmartPost")]
    FedExSmartPost,
    
    /// <remarks/>
    OSM,
    
    /// <remarks/>
    OnTrac,
    
    /// <remarks/>
    Streamlite,
    
    /// <remarks/>
    Newgistics,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Canada Post")]
    CanadaPost,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Blue Package")]
    BluePackage,
    
    /// <remarks/>
    Chronopost,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Deutsche Post")]
    DeutschePost,
    
    /// <remarks/>
    DPD,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("La Poste")]
    LaPoste,
    
    /// <remarks/>
    Parcelnet,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Poste Italiane")]
    PosteItaliane,
    
    /// <remarks/>
    SDA,
    
    /// <remarks/>
    Smartmail,
    
    /// <remarks/>
    FEDEX_JP,
    
    /// <remarks/>
    JP_EXPRESS,
    
    /// <remarks/>
    NITTSU,
    
    /// <remarks/>
    SAGAWA,
    
    /// <remarks/>
    YAMATO,
    
    /// <remarks/>
    BlueDart,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("AFL/Fedex")]
    AFLFedex,
    
    /// <remarks/>
    Aramex,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("India Post")]
    IndiaPost,
    
    /// <remarks/>
    Professional,
    
    /// <remarks/>
    DTDC,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Overnite Express")]
    OverniteExpress,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("First Flight")]
    FirstFlight,
    
    /// <remarks/>
    Delhivery,
    
    /// <remarks/>
    Lasership,
    
    /// <remarks/>
    Yodel,
    
    /// <remarks/>
    Other,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Amazon Shipping")]
    AmazonShipping,
    
    /// <remarks/>
    Seur,
    
    /// <remarks/>
    Correos,
    
    /// <remarks/>
    MRW,
    
    /// <remarks/>
    Endopack,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Chrono Express")]
    ChronoExpress,
    
    /// <remarks/>
    Nacex,
    
    /// <remarks/>
    Otro,
    
    /// <remarks/>
    Correios,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class StandardProductID : object, System.ComponentModel.INotifyPropertyChanged {
    
    private StandardProductIDType typeField;
    
    private string valueField;
    
    /// <remarks/>
    public StandardProductIDType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
            this.RaisePropertyChanged("Type");
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
            this.RaisePropertyChanged("Value");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum StandardProductIDType {
    
    /// <remarks/>
    ISBN,
    
    /// <remarks/>
    UPC,
    
    /// <remarks/>
    EAN,
    
    /// <remarks/>
    ASIN,
    
    /// <remarks/>
    GTIN,
    
    /// <remarks/>
    GCID,
    
    /// <remarks/>
    PZN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class RelatedProductID : object, System.ComponentModel.INotifyPropertyChanged {
    
    private RelatedProductIDType typeField;
    
    private string valueField;
    
    /// <remarks/>
    public RelatedProductIDType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
            this.RaisePropertyChanged("Type");
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
            this.RaisePropertyChanged("Value");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum RelatedProductIDType {
    
    /// <remarks/>
    UPC,
    
    /// <remarks/>
    EAN,
    
    /// <remarks/>
    GTIN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum ConditionType {
    
    /// <remarks/>
    New,
    
    /// <remarks/>
    UsedLikeNew,
    
    /// <remarks/>
    UsedVeryGood,
    
    /// <remarks/>
    UsedGood,
    
    /// <remarks/>
    UsedAcceptable,
    
    /// <remarks/>
    CollectibleLikeNew,
    
    /// <remarks/>
    CollectibleVeryGood,
    
    /// <remarks/>
    CollectibleGood,
    
    /// <remarks/>
    CollectibleAcceptable,
    
    /// <remarks/>
    Refurbished,
    
    /// <remarks/>
    Club,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ComputerPlatform : object, System.ComponentModel.INotifyPropertyChanged {
    
    private ComputerPlatformType typeField;
    
    private string systemRequirementsField;
    
    /// <remarks/>
    public ComputerPlatformType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
            this.RaisePropertyChanged("Type");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SystemRequirements {
        get {
            return this.systemRequirementsField;
        }
        set {
            this.systemRequirementsField = value;
            this.RaisePropertyChanged("SystemRequirements");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ComputerPlatformType {
    
    /// <remarks/>
    windows,
    
    /// <remarks/>
    mac,
    
    /// <remarks/>
    linux,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ColorSpecification : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string colorField;
    
    private ColorMap colorMapField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
            this.RaisePropertyChanged("Color");
        }
    }
    
    /// <remarks/>
    public ColorMap ColorMap {
        get {
            return this.colorMapField;
        }
        set {
            this.colorMapField = value;
            this.RaisePropertyChanged("ColorMap");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum ColorMap {
    
    /// <remarks/>
    beige,
    
    /// <remarks/>
    black,
    
    /// <remarks/>
    blue,
    
    /// <remarks/>
    brass,
    
    /// <remarks/>
    bronze,
    
    /// <remarks/>
    brown,
    
    /// <remarks/>
    burst,
    
    /// <remarks/>
    chrome,
    
    /// <remarks/>
    clear,
    
    /// <remarks/>
    gold,
    
    /// <remarks/>
    gray,
    
    /// <remarks/>
    green,
    
    /// <remarks/>
    metallic,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("multi-colored")]
    multicolored,
    
    /// <remarks/>
    natural,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("off-white")]
    offwhite,
    
    /// <remarks/>
    orange,
    
    /// <remarks/>
    pink,
    
    /// <remarks/>
    purple,
    
    /// <remarks/>
    red,
    
    /// <remarks/>
    silver,
    
    /// <remarks/>
    white,
    
    /// <remarks/>
    yellow,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum DeliveryChannel {
    
    /// <remarks/>
    in_store,
    
    /// <remarks/>
    direct_ship,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("CharacterData", Namespace="", IsNullable=false)]
public partial class CharacterDataType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string sKUField;
    
    private System.DateTime effectiveTimestampField;
    
    private bool effectiveTimestampFieldSpecified;
    
    private string[] pluginField;
    
    private string additionalMessageDiscriminatorField;
    
    private string payloadField;
    
    private string schemaVersionField;
    
    private bool isOfferOnlyUpdateField;
    
    private bool isOfferOnlyUpdateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SKU {
        get {
            return this.sKUField;
        }
        set {
            this.sKUField = value;
            this.RaisePropertyChanged("SKU");
        }
    }
    
    /// <remarks/>
    public System.DateTime EffectiveTimestamp {
        get {
            return this.effectiveTimestampField;
        }
        set {
            this.effectiveTimestampField = value;
            this.RaisePropertyChanged("EffectiveTimestamp");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EffectiveTimestampSpecified {
        get {
            return this.effectiveTimestampFieldSpecified;
        }
        set {
            this.effectiveTimestampFieldSpecified = value;
            this.RaisePropertyChanged("EffectiveTimestampSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Plugin")]
    public string[] Plugin {
        get {
            return this.pluginField;
        }
        set {
            this.pluginField = value;
            this.RaisePropertyChanged("Plugin");
        }
    }
    
    /// <remarks/>
    public string AdditionalMessageDiscriminator {
        get {
            return this.additionalMessageDiscriminatorField;
        }
        set {
            this.additionalMessageDiscriminatorField = value;
            this.RaisePropertyChanged("AdditionalMessageDiscriminator");
        }
    }
    
    /// <remarks/>
    public string Payload {
        get {
            return this.payloadField;
        }
        set {
            this.payloadField = value;
            this.RaisePropertyChanged("Payload");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
            this.RaisePropertyChanged("schemaVersion");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isOfferOnlyUpdate {
        get {
            return this.isOfferOnlyUpdateField;
        }
        set {
            this.isOfferOnlyUpdateField = value;
            this.RaisePropertyChanged("isOfferOnlyUpdate");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isOfferOnlyUpdateSpecified {
        get {
            return this.isOfferOnlyUpdateFieldSpecified;
        }
        set {
            this.isOfferOnlyUpdateFieldSpecified = value;
            this.RaisePropertyChanged("isOfferOnlyUpdateSpecified");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Recall : object, System.ComponentModel.INotifyPropertyChanged {
    
    private bool isRecalledField;
    
    private string recallDescriptionField;
    
    /// <remarks/>
    public bool IsRecalled {
        get {
            return this.isRecalledField;
        }
        set {
            this.isRecalledField = value;
            this.RaisePropertyChanged("IsRecalled");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RecallDescription {
        get {
            return this.recallDescriptionField;
        }
        set {
            this.recallDescriptionField = value;
            this.RaisePropertyChanged("RecallDescription");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class AgeRecommendation : object, System.ComponentModel.INotifyPropertyChanged {
    
    private MinimumAgeRecommendedDimension minimumManufacturerAgeRecommendedField;
    
    private AgeRecommendedDimension maximumManufacturerAgeRecommendedField;
    
    private MinimumAgeRecommendedDimension minimumMerchantAgeRecommendedField;
    
    private AgeRecommendedDimension maximumMerchantAgeRecommendedField;
    
    /// <remarks/>
    public MinimumAgeRecommendedDimension MinimumManufacturerAgeRecommended {
        get {
            return this.minimumManufacturerAgeRecommendedField;
        }
        set {
            this.minimumManufacturerAgeRecommendedField = value;
            this.RaisePropertyChanged("MinimumManufacturerAgeRecommended");
        }
    }
    
    /// <remarks/>
    public AgeRecommendedDimension MaximumManufacturerAgeRecommended {
        get {
            return this.maximumManufacturerAgeRecommendedField;
        }
        set {
            this.maximumManufacturerAgeRecommendedField = value;
            this.RaisePropertyChanged("MaximumManufacturerAgeRecommended");
        }
    }
    
    /// <remarks/>
    public MinimumAgeRecommendedDimension MinimumMerchantAgeRecommended {
        get {
            return this.minimumMerchantAgeRecommendedField;
        }
        set {
            this.minimumMerchantAgeRecommendedField = value;
            this.RaisePropertyChanged("MinimumMerchantAgeRecommended");
        }
    }
    
    /// <remarks/>
    public AgeRecommendedDimension MaximumMerchantAgeRecommended {
        get {
            return this.maximumMerchantAgeRecommendedField;
        }
        set {
            this.maximumMerchantAgeRecommendedField = value;
            this.RaisePropertyChanged("MaximumMerchantAgeRecommended");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class WeightRecommendation : object, System.ComponentModel.INotifyPropertyChanged {
    
    private WeightIntegerDimension minimumManufacturerWeightRecommendedField;
    
    private WeightIntegerDimension maximumManufacturerWeightRecommendedField;
    
    /// <remarks/>
    public WeightIntegerDimension MinimumManufacturerWeightRecommended {
        get {
            return this.minimumManufacturerWeightRecommendedField;
        }
        set {
            this.minimumManufacturerWeightRecommendedField = value;
            this.RaisePropertyChanged("MinimumManufacturerWeightRecommended");
        }
    }
    
    /// <remarks/>
    public WeightIntegerDimension MaximumManufacturerWeightRecommended {
        get {
            return this.maximumManufacturerWeightRecommendedField;
        }
        set {
            this.maximumManufacturerWeightRecommendedField = value;
            this.RaisePropertyChanged("MaximumManufacturerWeightRecommended");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class HeightRecommendation : object, System.ComponentModel.INotifyPropertyChanged {
    
    private LengthDimension minimumHeightRecommendedField;
    
    private LengthDimension maximumHeightRecommendedField;
    
    /// <remarks/>
    public LengthDimension MinimumHeightRecommended {
        get {
            return this.minimumHeightRecommendedField;
        }
        set {
            this.minimumHeightRecommendedField = value;
            this.RaisePropertyChanged("MinimumHeightRecommended");
        }
    }
    
    /// <remarks/>
    public LengthDimension MaximumHeightRecommended {
        get {
            return this.maximumHeightRecommendedField;
        }
        set {
            this.maximumHeightRecommendedField = value;
            this.RaisePropertyChanged("MaximumHeightRecommended");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ForwardFacingWeight : object, System.ComponentModel.INotifyPropertyChanged {
    
    private WeightDimension forwardFacingMaximumWeightField;
    
    private WeightDimension forwardFacingMinimumWeightField;
    
    /// <remarks/>
    public WeightDimension ForwardFacingMaximumWeight {
        get {
            return this.forwardFacingMaximumWeightField;
        }
        set {
            this.forwardFacingMaximumWeightField = value;
            this.RaisePropertyChanged("ForwardFacingMaximumWeight");
        }
    }
    
    /// <remarks/>
    public WeightDimension ForwardFacingMinimumWeight {
        get {
            return this.forwardFacingMinimumWeightField;
        }
        set {
            this.forwardFacingMinimumWeightField = value;
            this.RaisePropertyChanged("ForwardFacingMinimumWeight");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class RearFacingWeight : object, System.ComponentModel.INotifyPropertyChanged {
    
    private WeightDimension rearFacingMaximumWeightField;
    
    private WeightDimension rearFacingMinimumWeightField;
    
    /// <remarks/>
    public WeightDimension RearFacingMaximumWeight {
        get {
            return this.rearFacingMaximumWeightField;
        }
        set {
            this.rearFacingMaximumWeightField = value;
            this.RaisePropertyChanged("RearFacingMaximumWeight");
        }
    }
    
    /// <remarks/>
    public WeightDimension RearFacingMinimumWeight {
        get {
            return this.rearFacingMinimumWeightField;
        }
        set {
            this.rearFacingMinimumWeightField = value;
            this.RaisePropertyChanged("RearFacingMinimumWeight");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ShoulderHarnessHeight : object, System.ComponentModel.INotifyPropertyChanged {
    
    private LengthDimension shoulderHarnessMaximumHeightField;
    
    private LengthDimension shoulderHarnessMinimumHeightField;
    
    /// <remarks/>
    public LengthDimension ShoulderHarnessMaximumHeight {
        get {
            return this.shoulderHarnessMaximumHeightField;
        }
        set {
            this.shoulderHarnessMaximumHeightField = value;
            this.RaisePropertyChanged("ShoulderHarnessMaximumHeight");
        }
    }
    
    /// <remarks/>
    public LengthDimension ShoulderHarnessMinimumHeight {
        get {
            return this.shoulderHarnessMinimumHeightField;
        }
        set {
            this.shoulderHarnessMinimumHeightField = value;
            this.RaisePropertyChanged("ShoulderHarnessMinimumHeight");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Inventory : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string sKUField;
    
    private string fulfillmentCenterIDField;
    
    private object itemField;
    
    private System.DateTime restockDateField;
    
    private bool restockDateFieldSpecified;
    
    private string fulfillmentLatencyField;
    
    private InventorySwitchFulfillmentTo switchFulfillmentToField;
    
    private bool switchFulfillmentToFieldSpecified;
	private string available;
	private int quantity;
	private string lookup;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SKU {
        get {
            return this.sKUField;
        }
        set {
            this.sKUField = value;
            this.RaisePropertyChanged("SKU");
        }
    }
	public string Available
	{
		get
		{
			return this.available;
		}
		set
		{
			this.available = value;
			this.RaisePropertyChanged("Available");
		}
	}
	public int Quantity
	{
		get
		{
			return this.quantity;
		}
		set
		{
			this.quantity = value;
			this.RaisePropertyChanged("Quantity");
		}
	}
	public string Lookup
	{
		get
		{
			return this.lookup;
		}
		set
		{
			this.lookup = value;
			this.RaisePropertyChanged("Lookup");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FulfillmentCenterID {
        get {
            return this.fulfillmentCenterIDField;
        }
        set {
            this.fulfillmentCenterIDField = value;
            this.RaisePropertyChanged("FulfillmentCenterID");
        }
    }
    
    /// <remarks/>
    //[System.Xml.Serialization.XmlElementAttribute("Available", typeof(bool))]
    //[System.Xml.Serialization.XmlElementAttribute("Lookup", typeof(InventoryLookup))]
    //[System.Xml.Serialization.XmlElementAttribute("Quantity", typeof(string), DataType="nonNegativeInteger")]
    //public object Item {
    //    get {
    //        return this.itemField;
    //    }
    //    set {
    //        this.itemField = value;
    //        this.RaisePropertyChanged("Item");
    //    }
    //}
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime RestockDate {
        get {
            return this.restockDateField;
        }
        set {
            this.restockDateField = value;
            this.RaisePropertyChanged("RestockDate");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RestockDateSpecified {
        get {
            return this.restockDateFieldSpecified;
        }
        set {
            this.restockDateFieldSpecified = value;
            this.RaisePropertyChanged("RestockDateSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string FulfillmentLatency {
        get {
            return this.fulfillmentLatencyField;
        }
        set {
            this.fulfillmentLatencyField = value;
            this.RaisePropertyChanged("FulfillmentLatency");
        }
    }
    
    /// <remarks/>
    public InventorySwitchFulfillmentTo SwitchFulfillmentTo {
        get {
            return this.switchFulfillmentToField;
        }
        set {
            this.switchFulfillmentToField = value;
            this.RaisePropertyChanged("SwitchFulfillmentTo");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SwitchFulfillmentToSpecified {
        get {
            return this.switchFulfillmentToFieldSpecified;
        }
        set {
            this.switchFulfillmentToFieldSpecified = value;
            this.RaisePropertyChanged("SwitchFulfillmentToSpecified");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum InventoryLookup {
    
    /// <remarks/>
    FulfillmentNetwork,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum InventorySwitchFulfillmentTo {
    
    /// <remarks/>
    MFN,
    
    /// <remarks/>
    AFN,
}
