//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace AmazonAPI.Feeds.MarketplaceWebService.Model
{

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlRootAttribute("Address", Namespace = "", IsNullable = false)]
	public partial class AddressType
	{

		private string nameField;

		private string formalTitleField;

		private string givenNameField;

		private string familyNameField;

		private string addressFieldOneField;

		private string addressFieldTwoField;

		private string addressFieldThreeField;

		private string cityField;

		private string countyField;

		private string stateOrRegionField;

		private string postalCodeField;

		private string countryCodeField;

		private PhoneNumberType[] phoneNumberField;

		private bool isDefaultShippingField;

		private bool isDefaultShippingFieldSpecified;

		private bool isDefaultBillingField;

		private bool isDefaultBillingFieldSpecified;

		private bool isDefaultOneClickField;

		private bool isDefaultOneClickFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string FormalTitle
		{
			get
			{
				return this.formalTitleField;
			}
			set
			{
				this.formalTitleField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string GivenName
		{
			get
			{
				return this.givenNameField;
			}
			set
			{
				this.givenNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string FamilyName
		{
			get
			{
				return this.familyNameField;
			}
			set
			{
				this.familyNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string AddressFieldOne
		{
			get
			{
				return this.addressFieldOneField;
			}
			set
			{
				this.addressFieldOneField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string AddressFieldTwo
		{
			get
			{
				return this.addressFieldTwoField;
			}
			set
			{
				this.addressFieldTwoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string AddressFieldThree
		{
			get
			{
				return this.addressFieldThreeField;
			}
			set
			{
				this.addressFieldThreeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string City
		{
			get
			{
				return this.cityField;
			}
			set
			{
				this.cityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string County
		{
			get
			{
				return this.countyField;
			}
			set
			{
				this.countyField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string StateOrRegion
		{
			get
			{
				return this.stateOrRegionField;
			}
			set
			{
				this.stateOrRegionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string PostalCode
		{
			get
			{
				return this.postalCodeField;
			}
			set
			{
				this.postalCodeField = value;
			}
		}

		/// <remarks/>
		public string CountryCode
		{
			get
			{
				return this.countryCodeField;
			}
			set
			{
				this.countryCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("PhoneNumber")]
		public PhoneNumberType[] PhoneNumber
		{
			get
			{
				return this.phoneNumberField;
			}
			set
			{
				this.phoneNumberField = value;
			}
		}

		/// <remarks/>
		public bool isDefaultShipping
		{
			get
			{
				return this.isDefaultShippingField;
			}
			set
			{
				this.isDefaultShippingField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool isDefaultShippingSpecified
		{
			get
			{
				return this.isDefaultShippingFieldSpecified;
			}
			set
			{
				this.isDefaultShippingFieldSpecified = value;
			}
		}

		/// <remarks/>
		public bool isDefaultBilling
		{
			get
			{
				return this.isDefaultBillingField;
			}
			set
			{
				this.isDefaultBillingField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool isDefaultBillingSpecified
		{
			get
			{
				return this.isDefaultBillingFieldSpecified;
			}
			set
			{
				this.isDefaultBillingFieldSpecified = value;
			}
		}

		/// <remarks/>
		public bool isDefaultOneClick
		{
			get
			{
				return this.isDefaultOneClickField;
			}
			set
			{
				this.isDefaultOneClickField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool isDefaultOneClickSpecified
		{
			get
			{
				return this.isDefaultOneClickFieldSpecified;
			}
			set
			{
				this.isDefaultOneClickFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class PhoneNumberType
	{

		private PhoneNumberTypeType typeField;

		private bool typeFieldSpecified;

		private string descriptionField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public PhoneNumberTypeType Type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool TypeSpecified
		{
			get
			{
				return this.typeFieldSpecified;
			}
			set
			{
				this.typeFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute(DataType = "normalizedString")]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum PhoneNumberTypeType
	{

		/// <remarks/>
		Voice,

		/// <remarks/>
		Fax,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class DatedPrice
	{

		private System.DateTime startDateField;

		private bool startDateFieldSpecified;

		private System.DateTime endDateField;

		private bool endDateFieldSpecified;

		private CurrencyAmount itemField;

		private ItemChoiceType itemElementNameField;

		private bool deleteField;

		private bool deleteFieldSpecified;

		/// <remarks/>
		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool StartDateSpecified
		{
			get
			{
				return this.startDateFieldSpecified;
			}
			set
			{
				this.startDateFieldSpecified = value;
			}
		}

		/// <remarks/>
		public System.DateTime EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool EndDateSpecified
		{
			get
			{
				return this.endDateFieldSpecified;
			}
			set
			{
				this.endDateFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("PreviousPrice", typeof(CurrencyAmount))]
		[System.Xml.Serialization.XmlElementAttribute("Price", typeof(CurrencyAmount))]
		[System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
		public CurrencyAmount Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public ItemChoiceType ItemElementName
		{
			get
			{
				return this.itemElementNameField;
			}
			set
			{
				this.itemElementNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool delete
		{
			get
			{
				return this.deleteField;
			}
			set
			{
				this.deleteField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool deleteSpecified
		{
			get
			{
				return this.deleteFieldSpecified;
			}
			set
			{
				this.deleteFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class CurrencyAmount
	{

		private BaseCurrencyCode currencyField;

		private bool currencyFieldSpecified;

		private decimal valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public BaseCurrencyCode currency
		{
			get
			{
				return this.currencyField;
			}
			set
			{
				this.currencyField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool currencySpecified
		{
			get
			{
				return this.currencyFieldSpecified;
			}
			set
			{
				this.currencyFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public decimal Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	public enum BaseCurrencyCode
	{

		/// <remarks/>
		USD,

		/// <remarks/>
		GBP,

		/// <remarks/>
		EUR,

		/// <remarks/>
		JPY,

		/// <remarks/>
		CAD,

		/// <remarks/>
		CNY,

		/// <remarks/>
		INR,

		/// <remarks/>
		MXN,

		/// <remarks/>
		BRL,

		/// <remarks/>
		AUD,

		/// <remarks/>
		TRY,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
	public enum ItemChoiceType
	{

		/// <remarks/>
		PreviousPrice,

		/// <remarks/>
		Price,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class DatedCompareAtPrice
	{

		private System.DateTime startDateField;

		private bool startDateFieldSpecified;

		private System.DateTime endDateField;

		private bool endDateFieldSpecified;

		private CurrencyAmount compareAtPriceField;

		private bool deleteField;

		private bool deleteFieldSpecified;

		/// <remarks/>
		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool StartDateSpecified
		{
			get
			{
				return this.startDateFieldSpecified;
			}
			set
			{
				this.startDateFieldSpecified = value;
			}
		}

		/// <remarks/>
		public System.DateTime EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool EndDateSpecified
		{
			get
			{
				return this.endDateFieldSpecified;
			}
			set
			{
				this.endDateFieldSpecified = value;
			}
		}

		/// <remarks/>
		public CurrencyAmount CompareAtPrice
		{
			get
			{
				return this.compareAtPriceField;
			}
			set
			{
				this.compareAtPriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool delete
		{
			get
			{
				return this.deleteField;
			}
			set
			{
				this.deleteField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool deleteSpecified
		{
			get
			{
				return this.deleteFieldSpecified;
			}
			set
			{
				this.deleteFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(StringOverrideCurrencyAmount))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class StringCurrencyAmountWithDefault
	{

		private BaseCurrencyCodeWithDefault currencyField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public BaseCurrencyCodeWithDefault currency
		{
			get
			{
				return this.currencyField;
			}
			set
			{
				this.currencyField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	public enum BaseCurrencyCodeWithDefault
	{

		/// <remarks/>
		USD,

		/// <remarks/>
		GBP,

		/// <remarks/>
		EUR,

		/// <remarks/>
		JPY,

		/// <remarks/>
		CAD,

		/// <remarks/>
		CNY,

		/// <remarks/>
		INR,

		/// <remarks/>
		AUD,

		/// <remarks/>
		BRL,

		/// <remarks/>
		MXN,

		/// <remarks/>
		TRY,

		/// <remarks/>
		DEFAULT,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class StringOverrideCurrencyAmount : StringCurrencyAmountWithDefault
	{

		private bool zeroField;

		private bool zeroFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool zero
		{
			get
			{
				return this.zeroField;
			}
			set
			{
				this.zeroField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool zeroSpecified
		{
			get
			{
				return this.zeroFieldSpecified;
			}
			set
			{
				this.zeroFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OverrideCurrencyAmount))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OverrideCurrencyAmountWithTax))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class CurrencyAmountWithDefault
	{

		private BaseCurrencyCodeWithDefault currencyField;

		private decimal valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public BaseCurrencyCodeWithDefault currency
		{
			get
			{
				return this.currencyField;
			}
			set
			{
				this.currencyField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public decimal Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OverrideCurrencyAmountWithTax))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class OverrideCurrencyAmount : CurrencyAmountWithDefault
	{

		private bool zeroField;

		private bool zeroFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool zero
		{
			get
			{
				return this.zeroField;
			}
			set
			{
				this.zeroField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool zeroSpecified
		{
			get
			{
				return this.zeroFieldSpecified;
			}
			set
			{
				this.zeroFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class OverrideCurrencyAmountWithTax : OverrideCurrencyAmount
	{

		private decimal valueWithoutTaxField;

		private bool valueWithoutTaxFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal valueWithoutTax
		{
			get
			{
				return this.valueWithoutTaxField;
			}
			set
			{
				this.valueWithoutTaxField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool valueWithoutTaxSpecified
		{
			get
			{
				return this.valueWithoutTaxFieldSpecified;
			}
			set
			{
				this.valueWithoutTaxFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class WeightDimension
	{

		private WeightUnitOfMeasure unitOfMeasureField;

		private decimal valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public WeightUnitOfMeasure unitOfMeasure
		{
			get
			{
				return this.unitOfMeasureField;
			}
			set
			{
				this.unitOfMeasureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public decimal Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	public enum WeightUnitOfMeasure
	{

		/// <remarks/>
		GR,

		/// <remarks/>
		KG,

		/// <remarks/>
		OZ,

		/// <remarks/>
		LB,

		/// <remarks/>
		MG,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class LengthDimension
	{

		private LengthUnitOfMeasure unitOfMeasureField;

		private decimal valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public LengthUnitOfMeasure unitOfMeasure
		{
			get
			{
				return this.unitOfMeasureField;
			}
			set
			{
				this.unitOfMeasureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public decimal Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	public enum LengthUnitOfMeasure
	{

		/// <remarks/>
		MM,

		/// <remarks/>
		CM,

		/// <remarks/>
		M,

		/// <remarks/>
		IN,

		/// <remarks/>
		FT,

		/// <remarks/>
		inches,

		/// <remarks/>
		feet,

		/// <remarks/>
		meters,

		/// <remarks/>
		decimeters,

		/// <remarks/>
		centimeters,

		/// <remarks/>
		millimeters,

		/// <remarks/>
		micrometers,

		/// <remarks/>
		nanometers,

		/// <remarks/>
		picometers,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class WeightIntegerDimension
	{

		private WeightUnitOfMeasure unitOfMeasureField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public WeightUnitOfMeasure unitOfMeasure
		{
			get
			{
				return this.unitOfMeasureField;
			}
			set
			{
				this.unitOfMeasureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute(DataType = "positiveInteger")]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class AgeRecommendedDimension
	{

		private AgeRecommendedUnitOfMeasure unitOfMeasureField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public AgeRecommendedUnitOfMeasure unitOfMeasure
		{
			get
			{
				return this.unitOfMeasureField;
			}
			set
			{
				this.unitOfMeasureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute(DataType = "positiveInteger")]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	public enum AgeRecommendedUnitOfMeasure
	{

		/// <remarks/>
		months,

		/// <remarks/>
		years,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class MinimumAgeRecommendedDimension
	{

		private AgeRecommendedUnitOfMeasure unitOfMeasureField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public AgeRecommendedUnitOfMeasure unitOfMeasure
		{
			get
			{
				return this.unitOfMeasureField;
			}
			set
			{
				this.unitOfMeasureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute(DataType = "nonNegativeInteger")]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Battery
	{

		private bool areBatteriesIncludedField;

		private bool areBatteriesIncludedFieldSpecified;

		private bool areBatteriesRequiredField;

		private bool areBatteriesRequiredFieldSpecified;

		private BatteryBatterySubgroup[] batterySubgroupField;

		/// <remarks/>
		public bool AreBatteriesIncluded
		{
			get
			{
				return this.areBatteriesIncludedField;
			}
			set
			{
				this.areBatteriesIncludedField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool AreBatteriesIncludedSpecified
		{
			get
			{
				return this.areBatteriesIncludedFieldSpecified;
			}
			set
			{
				this.areBatteriesIncludedFieldSpecified = value;
			}
		}

		/// <remarks/>
		public bool AreBatteriesRequired
		{
			get
			{
				return this.areBatteriesRequiredField;
			}
			set
			{
				this.areBatteriesRequiredField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool AreBatteriesRequiredSpecified
		{
			get
			{
				return this.areBatteriesRequiredFieldSpecified;
			}
			set
			{
				this.areBatteriesRequiredFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("BatterySubgroup")]
		public BatteryBatterySubgroup[] BatterySubgroup
		{
			get
			{
				return this.batterySubgroupField;
			}
			set
			{
				this.batterySubgroupField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class BatteryBatterySubgroup
	{

		private BatteryBatterySubgroupBatteryType batteryTypeField;

		private string numberOfBatteriesField;

		/// <remarks/>
		public BatteryBatterySubgroupBatteryType BatteryType
		{
			get
			{
				return this.batteryTypeField;
			}
			set
			{
				this.batteryTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
		public string NumberOfBatteries
		{
			get
			{
				return this.numberOfBatteriesField;
			}
			set
			{
				this.numberOfBatteriesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum BatteryBatterySubgroupBatteryType
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("battery_type_2/3A")]
		battery_type_23A,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("battery_type_4/3A")]
		battery_type_43A,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("battery_type_4/5A")]
		battery_type_45A,

		/// <remarks/>
		battery_type_9v,

		/// <remarks/>
		battery_type_12v,

		/// <remarks/>
		battery_type_a,

		/// <remarks/>
		battery_type_a76,

		/// <remarks/>
		battery_type_aa,

		/// <remarks/>
		battery_type_aaa,

		/// <remarks/>
		battery_type_aaaa,

		/// <remarks/>
		battery_type_c,

		/// <remarks/>
		battery_type_cr123a,

		/// <remarks/>
		battery_type_cr2,

		/// <remarks/>
		battery_type_cr5,

		/// <remarks/>
		battery_type_d,

		/// <remarks/>
		battery_type_lithium_ion,

		/// <remarks/>
		battery_type_lithium_metal,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("battery_type_L-SC")]
		battery_type_LSC,

		/// <remarks/>
		battery_type_p76,

		/// <remarks/>
		battery_type_product_specific,

		/// <remarks/>
		battery_type_SC,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public enum FulfillmentMethod
	{

		/// <remarks/>
		Ship,

		/// <remarks/>
		InStorePickup,

		/// <remarks/>
		MerchantDelivery,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public enum FulfillmentServiceLevel
	{

		/// <remarks/>
		Standard,

		/// <remarks/>
		Expedited,

		/// <remarks/>
		Scheduled,

		/// <remarks/>
		NextDay,

		/// <remarks/>
		SecondDay,

		/// <remarks/>
		Next,

		/// <remarks/>
		Second,

		/// <remarks/>
		Priority,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public enum CarrierCode
	{

		/// <remarks/>
		USPS,

		/// <remarks/>
		UPS,

		/// <remarks/>
		UPSMI,

		/// <remarks/>
		FedEx,

		/// <remarks/>
		DHL,

		/// <remarks/>
		Fastway,

		/// <remarks/>
		GLS,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("GO!")]
		GO,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("Hermes Logistik Gruppe")]
		HermesLogistikGruppe,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("Royal Mail")]
		RoyalMail,

		/// <remarks/>
		Parcelforce,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("City Link")]
		CityLink,

		/// <remarks/>
		TNT,

		/// <remarks/>
		Target,

		/// <remarks/>
		SagawaExpress,

		/// <remarks/>
		NipponExpress,

		/// <remarks/>
		YamatoTransport,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("DHL Global Mail")]
		DHLGlobalMail,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("UPS Mail Innovations")]
		UPSMailInnovations,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("FedEx SmartPost")]
		FedExSmartPost,

		/// <remarks/>
		OSM,

		/// <remarks/>
		OnTrac,

		/// <remarks/>
		Streamlite,

		/// <remarks/>
		Newgistics,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("Canada Post")]
		CanadaPost,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("Blue Package")]
		BluePackage,

		/// <remarks/>
		Chronopost,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("Deutsche Post")]
		DeutschePost,

		/// <remarks/>
		DPD,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("La Poste")]
		LaPoste,

		/// <remarks/>
		Parcelnet,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("Poste Italiane")]
		PosteItaliane,

		/// <remarks/>
		SDA,

		/// <remarks/>
		Smartmail,

		/// <remarks/>
		FEDEX_JP,

		/// <remarks/>
		JP_EXPRESS,

		/// <remarks/>
		NITTSU,

		/// <remarks/>
		SAGAWA,

		/// <remarks/>
		YAMATO,

		/// <remarks/>
		BlueDart,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("AFL/Fedex")]
		AFLFedex,

		/// <remarks/>
		Aramex,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("India Post")]
		IndiaPost,

		/// <remarks/>
		Professional,

		/// <remarks/>
		DTDC,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("Overnite Express")]
		OverniteExpress,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("First Flight")]
		FirstFlight,

		/// <remarks/>
		Delhivery,

		/// <remarks/>
		Lasership,

		/// <remarks/>
		Yodel,

		/// <remarks/>
		Other,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("Amazon Shipping")]
		AmazonShipping,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class StandardProductID
	{

		private StandardProductIDType typeField;

		private string valueField;

		/// <remarks/>
		public StandardProductIDType Type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum StandardProductIDType
	{

		/// <remarks/>
		ISBN,

		/// <remarks/>
		UPC,

		/// <remarks/>
		EAN,

		/// <remarks/>
		ASIN,

		/// <remarks/>
		GTIN,

		/// <remarks/>
		GCID,

		/// <remarks/>
		PZN,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class RelatedProductID
	{

		private RelatedProductIDType typeField;

		private string valueField;

		/// <remarks/>
		public RelatedProductIDType Type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum RelatedProductIDType
	{

		/// <remarks/>
		UPC,

		/// <remarks/>
		EAN,

		/// <remarks/>
		GTIN,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public enum ConditionType
	{

		/// <remarks/>
		New,

		/// <remarks/>
		UsedLikeNew,

		/// <remarks/>
		UsedVeryGood,

		/// <remarks/>
		UsedGood,

		/// <remarks/>
		UsedAcceptable,

		/// <remarks/>
		CollectibleLikeNew,

		/// <remarks/>
		CollectibleVeryGood,

		/// <remarks/>
		CollectibleGood,

		/// <remarks/>
		CollectibleAcceptable,

		/// <remarks/>
		Refurbished,

		/// <remarks/>
		Club,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class ComputerPlatform
	{

		private ComputerPlatformType typeField;

		private string systemRequirementsField;

		/// <remarks/>
		public ComputerPlatformType Type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string SystemRequirements
		{
			get
			{
				return this.systemRequirementsField;
			}
			set
			{
				this.systemRequirementsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum ComputerPlatformType
	{

		/// <remarks/>
		windows,

		/// <remarks/>
		mac,

		/// <remarks/>
		linux,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class ColorSpecification
	{

		private string colorField;

		private ColorMap colorMapField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string Color
		{
			get
			{
				return this.colorField;
			}
			set
			{
				this.colorField = value;
			}
		}

		/// <remarks/>
		public ColorMap ColorMap
		{
			get
			{
				return this.colorMapField;
			}
			set
			{
				this.colorMapField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public enum ColorMap
	{

		/// <remarks/>
		beige,

		/// <remarks/>
		black,

		/// <remarks/>
		blue,

		/// <remarks/>
		brass,

		/// <remarks/>
		bronze,

		/// <remarks/>
		brown,

		/// <remarks/>
		burst,

		/// <remarks/>
		chrome,

		/// <remarks/>
		clear,

		/// <remarks/>
		gold,

		/// <remarks/>
		gray,

		/// <remarks/>
		green,

		/// <remarks/>
		metallic,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("multi-colored")]
		multicolored,

		/// <remarks/>
		natural,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("off-white")]
		offwhite,

		/// <remarks/>
		orange,

		/// <remarks/>
		pink,

		/// <remarks/>
		purple,

		/// <remarks/>
		red,

		/// <remarks/>
		silver,

		/// <remarks/>
		white,

		/// <remarks/>
		yellow,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public enum DeliveryChannel
	{

		/// <remarks/>
		in_store,

		/// <remarks/>
		direct_ship,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlRootAttribute("CharacterData", Namespace = "", IsNullable = false)]
	public partial class CharacterDataType
	{

		private string sKUField;

		private System.DateTime effectiveTimestampField;

		private bool effectiveTimestampFieldSpecified;

		private string[] pluginField;

		private string additionalMessageDiscriminatorField;

		private string payloadField;

		private string schemaVersionField;

		private bool isOfferOnlyUpdateField;

		private bool isOfferOnlyUpdateFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string SKU
		{
			get
			{
				return this.sKUField;
			}
			set
			{
				this.sKUField = value;
			}
		}

		/// <remarks/>
		public System.DateTime EffectiveTimestamp
		{
			get
			{
				return this.effectiveTimestampField;
			}
			set
			{
				this.effectiveTimestampField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool EffectiveTimestampSpecified
		{
			get
			{
				return this.effectiveTimestampFieldSpecified;
			}
			set
			{
				this.effectiveTimestampFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Plugin")]
		public string[] Plugin
		{
			get
			{
				return this.pluginField;
			}
			set
			{
				this.pluginField = value;
			}
		}

		/// <remarks/>
		public string AdditionalMessageDiscriminator
		{
			get
			{
				return this.additionalMessageDiscriminatorField;
			}
			set
			{
				this.additionalMessageDiscriminatorField = value;
			}
		}

		/// <remarks/>
		public string Payload
		{
			get
			{
				return this.payloadField;
			}
			set
			{
				this.payloadField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string schemaVersion
		{
			get
			{
				return this.schemaVersionField;
			}
			set
			{
				this.schemaVersionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool isOfferOnlyUpdate
		{
			get
			{
				return this.isOfferOnlyUpdateField;
			}
			set
			{
				this.isOfferOnlyUpdateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool isOfferOnlyUpdateSpecified
		{
			get
			{
				return this.isOfferOnlyUpdateFieldSpecified;
			}
			set
			{
				this.isOfferOnlyUpdateFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Recall
	{

		private bool isRecalledField;

		private string recallDescriptionField;

		/// <remarks/>
		public bool IsRecalled
		{
			get
			{
				return this.isRecalledField;
			}
			set
			{
				this.isRecalledField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string RecallDescription
		{
			get
			{
				return this.recallDescriptionField;
			}
			set
			{
				this.recallDescriptionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class AgeRecommendation
	{

		private MinimumAgeRecommendedDimension minimumManufacturerAgeRecommendedField;

		private AgeRecommendedDimension maximumManufacturerAgeRecommendedField;

		private MinimumAgeRecommendedDimension minimumMerchantAgeRecommendedField;

		private AgeRecommendedDimension maximumMerchantAgeRecommendedField;

		/// <remarks/>
		public MinimumAgeRecommendedDimension MinimumManufacturerAgeRecommended
		{
			get
			{
				return this.minimumManufacturerAgeRecommendedField;
			}
			set
			{
				this.minimumManufacturerAgeRecommendedField = value;
			}
		}

		/// <remarks/>
		public AgeRecommendedDimension MaximumManufacturerAgeRecommended
		{
			get
			{
				return this.maximumManufacturerAgeRecommendedField;
			}
			set
			{
				this.maximumManufacturerAgeRecommendedField = value;
			}
		}

		/// <remarks/>
		public MinimumAgeRecommendedDimension MinimumMerchantAgeRecommended
		{
			get
			{
				return this.minimumMerchantAgeRecommendedField;
			}
			set
			{
				this.minimumMerchantAgeRecommendedField = value;
			}
		}

		/// <remarks/>
		public AgeRecommendedDimension MaximumMerchantAgeRecommended
		{
			get
			{
				return this.maximumMerchantAgeRecommendedField;
			}
			set
			{
				this.maximumMerchantAgeRecommendedField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class WeightRecommendation
	{

		private WeightIntegerDimension minimumManufacturerWeightRecommendedField;

		private WeightIntegerDimension maximumManufacturerWeightRecommendedField;

		/// <remarks/>
		public WeightIntegerDimension MinimumManufacturerWeightRecommended
		{
			get
			{
				return this.minimumManufacturerWeightRecommendedField;
			}
			set
			{
				this.minimumManufacturerWeightRecommendedField = value;
			}
		}

		/// <remarks/>
		public WeightIntegerDimension MaximumManufacturerWeightRecommended
		{
			get
			{
				return this.maximumManufacturerWeightRecommendedField;
			}
			set
			{
				this.maximumManufacturerWeightRecommendedField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class HeightRecommendation
	{

		private LengthDimension minimumHeightRecommendedField;

		private LengthDimension maximumHeightRecommendedField;

		/// <remarks/>
		public LengthDimension MinimumHeightRecommended
		{
			get
			{
				return this.minimumHeightRecommendedField;
			}
			set
			{
				this.minimumHeightRecommendedField = value;
			}
		}

		/// <remarks/>
		public LengthDimension MaximumHeightRecommended
		{
			get
			{
				return this.maximumHeightRecommendedField;
			}
			set
			{
				this.maximumHeightRecommendedField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class ForwardFacingWeight
	{

		private WeightDimension forwardFacingMaximumWeightField;

		private WeightDimension forwardFacingMinimumWeightField;

		/// <remarks/>
		public WeightDimension ForwardFacingMaximumWeight
		{
			get
			{
				return this.forwardFacingMaximumWeightField;
			}
			set
			{
				this.forwardFacingMaximumWeightField = value;
			}
		}

		/// <remarks/>
		public WeightDimension ForwardFacingMinimumWeight
		{
			get
			{
				return this.forwardFacingMinimumWeightField;
			}
			set
			{
				this.forwardFacingMinimumWeightField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class RearFacingWeight
	{

		private WeightDimension rearFacingMaximumWeightField;

		private WeightDimension rearFacingMinimumWeightField;

		/// <remarks/>
		public WeightDimension RearFacingMaximumWeight
		{
			get
			{
				return this.rearFacingMaximumWeightField;
			}
			set
			{
				this.rearFacingMaximumWeightField = value;
			}
		}

		/// <remarks/>
		public WeightDimension RearFacingMinimumWeight
		{
			get
			{
				return this.rearFacingMinimumWeightField;
			}
			set
			{
				this.rearFacingMinimumWeightField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class ShoulderHarnessHeight
	{

		private LengthDimension shoulderHarnessMaximumHeightField;

		private LengthDimension shoulderHarnessMinimumHeightField;

		/// <remarks/>
		public LengthDimension ShoulderHarnessMaximumHeight
		{
			get
			{
				return this.shoulderHarnessMaximumHeightField;
			}
			set
			{
				this.shoulderHarnessMaximumHeightField = value;
			}
		}

		/// <remarks/>
		public LengthDimension ShoulderHarnessMinimumHeight
		{
			get
			{
				return this.shoulderHarnessMinimumHeightField;
			}
			set
			{
				this.shoulderHarnessMinimumHeightField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Price
	{

		private string sKUField;

		private OverrideCurrencyAmount standardPriceField;

		private string standardPricePointsField;

		private decimal businessPriceField;

		private bool businessPriceFieldSpecified;

		private QuantityPriceTypes quantityPriceTypeField;

		private bool quantityPriceTypeFieldSpecified;

		private PriceQuantityPrice quantityPriceField;

		private StringOverrideCurrencyAmount minimumSellerAllowedPriceField;

		private StringOverrideCurrencyAmount maximumSellerAllowedPriceField;

		private OverrideCurrencyAmount mAPField;

		private CurrencyAmountWithDefault depositAmountField;

		private PriceSale saleField;

		private DatedCompareAtPrice compareAtField;

		private DatedPrice previousField;

		private PriceRental_0 rental_0Field;

		private PriceRental_1 rental_1Field;

		private PriceRental_2 rental_2Field;

		private PriceRental_3 rental_3Field;

		private PriceRental_4 rental_4Field;

		private PriceRental_5 rental_5Field;

		private PriceRental_6 rental_6Field;

		private PriceRental_7 rental_7Field;

		private PriceRental_8 rental_8Field;

		private PriceRental_9 rental_9Field;

		private OverrideCurrencyAmount costPerClickBidPriceField;

		private bool makeAnOfferEligibilityField;

		private bool makeAnOfferEligibilityFieldSpecified;

		private decimal minimumAcceptPercentageField;

		private bool minimumAcceptPercentageFieldSpecified;

		private decimal maximumRejectPercentageField;

		private bool maximumRejectPercentageFieldSpecified;

		private PricingActionValues pricingActionField;

		private bool pricingActionFieldSpecified;

		private string metalStandardPriceField;

		private string diamondStandardPriceField;

		private string gemstoneStandardPriceField;

		private string makingChargesStandardPriceField;

		private string taxStandardPriceField;

		private string metalSalePriceField;

		private string diamondSalePriceField;

		private string gemstoneSalePriceField;

		private string makingChargesSalePriceField;

		private string taxSalePriceField;

		private OverrideCurrencyAmount maximumRetailPriceField;

		private IsSourcingOnDemandValues isSourcingOnDemandField;

		private bool isSourcingOnDemandFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string SKU
		{
			get
			{
				return this.sKUField;
			}
			set
			{
				this.sKUField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmount StandardPrice
		{
			get
			{
				return this.standardPriceField;
			}
			set
			{
				this.standardPriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
		public string StandardPricePoints
		{
			get
			{
				return this.standardPricePointsField;
			}
			set
			{
				this.standardPricePointsField = value;
			}
		}

		/// <remarks/>
		public decimal BusinessPrice
		{
			get
			{
				return this.businessPriceField;
			}
			set
			{
				this.businessPriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool BusinessPriceSpecified
		{
			get
			{
				return this.businessPriceFieldSpecified;
			}
			set
			{
				this.businessPriceFieldSpecified = value;
			}
		}

		/// <remarks/>
		public QuantityPriceTypes QuantityPriceType
		{
			get
			{
				return this.quantityPriceTypeField;
			}
			set
			{
				this.quantityPriceTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool QuantityPriceTypeSpecified
		{
			get
			{
				return this.quantityPriceTypeFieldSpecified;
			}
			set
			{
				this.quantityPriceTypeFieldSpecified = value;
			}
		}

		/// <remarks/>
		public PriceQuantityPrice QuantityPrice
		{
			get
			{
				return this.quantityPriceField;
			}
			set
			{
				this.quantityPriceField = value;
			}
		}

		/// <remarks/>
		public StringOverrideCurrencyAmount MinimumSellerAllowedPrice
		{
			get
			{
				return this.minimumSellerAllowedPriceField;
			}
			set
			{
				this.minimumSellerAllowedPriceField = value;
			}
		}

		/// <remarks/>
		public StringOverrideCurrencyAmount MaximumSellerAllowedPrice
		{
			get
			{
				return this.maximumSellerAllowedPriceField;
			}
			set
			{
				this.maximumSellerAllowedPriceField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmount MAP
		{
			get
			{
				return this.mAPField;
			}
			set
			{
				this.mAPField = value;
			}
		}

		/// <remarks/>
		public CurrencyAmountWithDefault DepositAmount
		{
			get
			{
				return this.depositAmountField;
			}
			set
			{
				this.depositAmountField = value;
			}
		}

		/// <remarks/>
		public PriceSale Sale
		{
			get
			{
				return this.saleField;
			}
			set
			{
				this.saleField = value;
			}
		}

		/// <remarks/>
		public DatedCompareAtPrice CompareAt
		{
			get
			{
				return this.compareAtField;
			}
			set
			{
				this.compareAtField = value;
			}
		}

		/// <remarks/>
		public DatedPrice Previous
		{
			get
			{
				return this.previousField;
			}
			set
			{
				this.previousField = value;
			}
		}

		/// <remarks/>
		public PriceRental_0 Rental_0
		{
			get
			{
				return this.rental_0Field;
			}
			set
			{
				this.rental_0Field = value;
			}
		}

		/// <remarks/>
		public PriceRental_1 Rental_1
		{
			get
			{
				return this.rental_1Field;
			}
			set
			{
				this.rental_1Field = value;
			}
		}

		/// <remarks/>
		public PriceRental_2 Rental_2
		{
			get
			{
				return this.rental_2Field;
			}
			set
			{
				this.rental_2Field = value;
			}
		}

		/// <remarks/>
		public PriceRental_3 Rental_3
		{
			get
			{
				return this.rental_3Field;
			}
			set
			{
				this.rental_3Field = value;
			}
		}

		/// <remarks/>
		public PriceRental_4 Rental_4
		{
			get
			{
				return this.rental_4Field;
			}
			set
			{
				this.rental_4Field = value;
			}
		}

		/// <remarks/>
		public PriceRental_5 Rental_5
		{
			get
			{
				return this.rental_5Field;
			}
			set
			{
				this.rental_5Field = value;
			}
		}

		/// <remarks/>
		public PriceRental_6 Rental_6
		{
			get
			{
				return this.rental_6Field;
			}
			set
			{
				this.rental_6Field = value;
			}
		}

		/// <remarks/>
		public PriceRental_7 Rental_7
		{
			get
			{
				return this.rental_7Field;
			}
			set
			{
				this.rental_7Field = value;
			}
		}

		/// <remarks/>
		public PriceRental_8 Rental_8
		{
			get
			{
				return this.rental_8Field;
			}
			set
			{
				this.rental_8Field = value;
			}
		}

		/// <remarks/>
		public PriceRental_9 Rental_9
		{
			get
			{
				return this.rental_9Field;
			}
			set
			{
				this.rental_9Field = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmount CostPerClickBidPrice
		{
			get
			{
				return this.costPerClickBidPriceField;
			}
			set
			{
				this.costPerClickBidPriceField = value;
			}
		}

		/// <remarks/>
		public bool MakeAnOfferEligibility
		{
			get
			{
				return this.makeAnOfferEligibilityField;
			}
			set
			{
				this.makeAnOfferEligibilityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool MakeAnOfferEligibilitySpecified
		{
			get
			{
				return this.makeAnOfferEligibilityFieldSpecified;
			}
			set
			{
				this.makeAnOfferEligibilityFieldSpecified = value;
			}
		}

		/// <remarks/>
		public decimal MinimumAcceptPercentage
		{
			get
			{
				return this.minimumAcceptPercentageField;
			}
			set
			{
				this.minimumAcceptPercentageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool MinimumAcceptPercentageSpecified
		{
			get
			{
				return this.minimumAcceptPercentageFieldSpecified;
			}
			set
			{
				this.minimumAcceptPercentageFieldSpecified = value;
			}
		}

		/// <remarks/>
		public decimal MaximumRejectPercentage
		{
			get
			{
				return this.maximumRejectPercentageField;
			}
			set
			{
				this.maximumRejectPercentageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool MaximumRejectPercentageSpecified
		{
			get
			{
				return this.maximumRejectPercentageFieldSpecified;
			}
			set
			{
				this.maximumRejectPercentageFieldSpecified = value;
			}
		}

		/// <remarks/>
		public PricingActionValues PricingAction
		{
			get
			{
				return this.pricingActionField;
			}
			set
			{
				this.pricingActionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool PricingActionSpecified
		{
			get
			{
				return this.pricingActionFieldSpecified;
			}
			set
			{
				this.pricingActionFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string MetalStandardPrice
		{
			get
			{
				return this.metalStandardPriceField;
			}
			set
			{
				this.metalStandardPriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string DiamondStandardPrice
		{
			get
			{
				return this.diamondStandardPriceField;
			}
			set
			{
				this.diamondStandardPriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string GemstoneStandardPrice
		{
			get
			{
				return this.gemstoneStandardPriceField;
			}
			set
			{
				this.gemstoneStandardPriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string MakingChargesStandardPrice
		{
			get
			{
				return this.makingChargesStandardPriceField;
			}
			set
			{
				this.makingChargesStandardPriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string TaxStandardPrice
		{
			get
			{
				return this.taxStandardPriceField;
			}
			set
			{
				this.taxStandardPriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string MetalSalePrice
		{
			get
			{
				return this.metalSalePriceField;
			}
			set
			{
				this.metalSalePriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string DiamondSalePrice
		{
			get
			{
				return this.diamondSalePriceField;
			}
			set
			{
				this.diamondSalePriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string GemstoneSalePrice
		{
			get
			{
				return this.gemstoneSalePriceField;
			}
			set
			{
				this.gemstoneSalePriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string MakingChargesSalePrice
		{
			get
			{
				return this.makingChargesSalePriceField;
			}
			set
			{
				this.makingChargesSalePriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
		public string TaxSalePrice
		{
			get
			{
				return this.taxSalePriceField;
			}
			set
			{
				this.taxSalePriceField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmount MaximumRetailPrice
		{
			get
			{
				return this.maximumRetailPriceField;
			}
			set
			{
				this.maximumRetailPriceField = value;
			}
		}

		/// <remarks/>
		public IsSourcingOnDemandValues IsSourcingOnDemand
		{
			get
			{
				return this.isSourcingOnDemandField;
			}
			set
			{
				this.isSourcingOnDemandField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool IsSourcingOnDemandSpecified
		{
			get
			{
				return this.isSourcingOnDemandFieldSpecified;
			}
			set
			{
				this.isSourcingOnDemandFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	public enum QuantityPriceTypes
	{

		/// <remarks/>
		@fixed,

		/// <remarks/>
		percent,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PriceQuantityPrice
	{

		private decimal quantityPrice1Field;

		private bool quantityPrice1FieldSpecified;

		private string quantityLowerBound1Field;

		private decimal quantityPrice2Field;

		private bool quantityPrice2FieldSpecified;

		private string quantityLowerBound2Field;

		private decimal quantityPrice3Field;

		private bool quantityPrice3FieldSpecified;

		private string quantityLowerBound3Field;

		private decimal quantityPrice4Field;

		private bool quantityPrice4FieldSpecified;

		private string quantityLowerBound4Field;

		private decimal quantityPrice5Field;

		private bool quantityPrice5FieldSpecified;

		private string quantityLowerBound5Field;

		/// <remarks/>
		public decimal QuantityPrice1
		{
			get
			{
				return this.quantityPrice1Field;
			}
			set
			{
				this.quantityPrice1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool QuantityPrice1Specified
		{
			get
			{
				return this.quantityPrice1FieldSpecified;
			}
			set
			{
				this.quantityPrice1FieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
		public string QuantityLowerBound1
		{
			get
			{
				return this.quantityLowerBound1Field;
			}
			set
			{
				this.quantityLowerBound1Field = value;
			}
		}

		/// <remarks/>
		public decimal QuantityPrice2
		{
			get
			{
				return this.quantityPrice2Field;
			}
			set
			{
				this.quantityPrice2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool QuantityPrice2Specified
		{
			get
			{
				return this.quantityPrice2FieldSpecified;
			}
			set
			{
				this.quantityPrice2FieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
		public string QuantityLowerBound2
		{
			get
			{
				return this.quantityLowerBound2Field;
			}
			set
			{
				this.quantityLowerBound2Field = value;
			}
		}

		/// <remarks/>
		public decimal QuantityPrice3
		{
			get
			{
				return this.quantityPrice3Field;
			}
			set
			{
				this.quantityPrice3Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool QuantityPrice3Specified
		{
			get
			{
				return this.quantityPrice3FieldSpecified;
			}
			set
			{
				this.quantityPrice3FieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
		public string QuantityLowerBound3
		{
			get
			{
				return this.quantityLowerBound3Field;
			}
			set
			{
				this.quantityLowerBound3Field = value;
			}
		}

		/// <remarks/>
		public decimal QuantityPrice4
		{
			get
			{
				return this.quantityPrice4Field;
			}
			set
			{
				this.quantityPrice4Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool QuantityPrice4Specified
		{
			get
			{
				return this.quantityPrice4FieldSpecified;
			}
			set
			{
				this.quantityPrice4FieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
		public string QuantityLowerBound4
		{
			get
			{
				return this.quantityLowerBound4Field;
			}
			set
			{
				this.quantityLowerBound4Field = value;
			}
		}

		/// <remarks/>
		public decimal QuantityPrice5
		{
			get
			{
				return this.quantityPrice5Field;
			}
			set
			{
				this.quantityPrice5Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool QuantityPrice5Specified
		{
			get
			{
				return this.quantityPrice5FieldSpecified;
			}
			set
			{
				this.quantityPrice5FieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
		public string QuantityLowerBound5
		{
			get
			{
				return this.quantityLowerBound5Field;
			}
			set
			{
				this.quantityLowerBound5Field = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PriceSale
	{

		private System.DateTime startDateField;

		private System.DateTime endDateField;

		private OverrideCurrencyAmount salePriceField;

		private string salePricePointsField;

		/// <remarks/>
		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <remarks/>
		public System.DateTime EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmount SalePrice
		{
			get
			{
				return this.salePriceField;
			}
			set
			{
				this.salePriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
		public string SalePricePoints
		{
			get
			{
				return this.salePricePointsField;
			}
			set
			{
				this.salePricePointsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PriceRental_0
	{

		private System.DateTime startDateField;

		private System.DateTime endDateField;

		private OverrideCurrencyAmountWithTax rentalPriceField;

		/// <remarks/>
		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <remarks/>
		public System.DateTime EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmountWithTax RentalPrice
		{
			get
			{
				return this.rentalPriceField;
			}
			set
			{
				this.rentalPriceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PriceRental_1
	{

		private System.DateTime startDateField;

		private System.DateTime endDateField;

		private OverrideCurrencyAmountWithTax rentalPriceField;

		/// <remarks/>
		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <remarks/>
		public System.DateTime EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmountWithTax RentalPrice
		{
			get
			{
				return this.rentalPriceField;
			}
			set
			{
				this.rentalPriceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PriceRental_2
	{

		private System.DateTime startDateField;

		private System.DateTime endDateField;

		private OverrideCurrencyAmountWithTax rentalPriceField;

		/// <remarks/>
		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <remarks/>
		public System.DateTime EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmountWithTax RentalPrice
		{
			get
			{
				return this.rentalPriceField;
			}
			set
			{
				this.rentalPriceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PriceRental_3
	{

		private System.DateTime startDateField;

		private System.DateTime endDateField;

		private OverrideCurrencyAmountWithTax rentalPriceField;

		/// <remarks/>
		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <remarks/>
		public System.DateTime EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmountWithTax RentalPrice
		{
			get
			{
				return this.rentalPriceField;
			}
			set
			{
				this.rentalPriceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PriceRental_4
	{

		private System.DateTime startDateField;

		private System.DateTime endDateField;

		private OverrideCurrencyAmountWithTax rentalPriceField;

		/// <remarks/>
		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <remarks/>
		public System.DateTime EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmountWithTax RentalPrice
		{
			get
			{
				return this.rentalPriceField;
			}
			set
			{
				this.rentalPriceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PriceRental_5
	{

		private System.DateTime startDateField;

		private System.DateTime endDateField;

		private OverrideCurrencyAmountWithTax rentalPriceField;

		/// <remarks/>
		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <remarks/>
		public System.DateTime EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmountWithTax RentalPrice
		{
			get
			{
				return this.rentalPriceField;
			}
			set
			{
				this.rentalPriceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PriceRental_6
	{

		private System.DateTime startDateField;

		private System.DateTime endDateField;

		private OverrideCurrencyAmountWithTax rentalPriceField;

		/// <remarks/>
		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <remarks/>
		public System.DateTime EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmountWithTax RentalPrice
		{
			get
			{
				return this.rentalPriceField;
			}
			set
			{
				this.rentalPriceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PriceRental_7
	{

		private System.DateTime startDateField;

		private System.DateTime endDateField;

		private OverrideCurrencyAmountWithTax rentalPriceField;

		/// <remarks/>
		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <remarks/>
		public System.DateTime EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmountWithTax RentalPrice
		{
			get
			{
				return this.rentalPriceField;
			}
			set
			{
				this.rentalPriceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PriceRental_8
	{

		private System.DateTime startDateField;

		private System.DateTime endDateField;

		private OverrideCurrencyAmountWithTax rentalPriceField;

		/// <remarks/>
		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <remarks/>
		public System.DateTime EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmountWithTax RentalPrice
		{
			get
			{
				return this.rentalPriceField;
			}
			set
			{
				this.rentalPriceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PriceRental_9
	{

		private System.DateTime startDateField;

		private System.DateTime endDateField;

		private OverrideCurrencyAmountWithTax rentalPriceField;

		/// <remarks/>
		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <remarks/>
		public System.DateTime EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		public OverrideCurrencyAmountWithTax RentalPrice
		{
			get
			{
				return this.rentalPriceField;
			}
			set
			{
				this.rentalPriceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	public enum PricingActionValues
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("delete business_price")]
		deletebusiness_price,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	public enum IsSourcingOnDemandValues
	{

		/// <remarks/>
		yes,

		/// <remarks/>
		no,
	}
}